In [ ]:
with open('sentences.txt','r') as file_sent:
  lines = file_sent.readlines() # создаём список из строк
  print(lines)

FileNotFoundError: ignored

In [ ]:
lines_temp = []
for line in lines: # перевод каждой строки в нижний регистр
  lines_temp.append(line.lower())
lines = lines_temp

In [ ]:
lines = list(map(lambda x: x.lower(), lines)) # 2 способ перевода каждой строки в нижний регистр

In [ ]:
import re
lines = list(map(lambda line: re.split('[^a-z]', line), lines))

In [ ]:
print(lines)

[['in', 'comparison', 'to', 'dogs', '', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process', '', ''], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', '', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', '', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes', '', ''], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output', '', ''], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', '', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals', '', ''], ['in', 'one', '', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', '', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin', '', ''], ['the', 'domesticated', 'cat', 'and', 'its', 'c

In [ ]:
lines = list(map(lambda line: list(filter(None, line)), lines))

In [ ]:
print(lines)

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

In [ ]:
for i in range(len(lines)):
  lines[i] = list(filter(None, lines[i]))

In [ ]:
print(lines)

[['in', 'comparison', 'to', 'dogs', 'cats', 'have', 'not', 'undergone', 'major', 'changes', 'during', 'the', 'domestication', 'process'], ['as', 'cat', 'simply', 'catenates', 'streams', 'of', 'bytes', 'it', 'can', 'be', 'also', 'used', 'to', 'concatenate', 'binary', 'files', 'where', 'it', 'will', 'just', 'concatenate', 'sequence', 'of', 'bytes'], ['a', 'common', 'interactive', 'use', 'of', 'cat', 'for', 'a', 'single', 'file', 'is', 'to', 'output', 'the', 'content', 'of', 'a', 'file', 'to', 'standard', 'output'], ['cats', 'can', 'hear', 'sounds', 'too', 'faint', 'or', 'too', 'high', 'in', 'frequency', 'for', 'human', 'ears', 'such', 'as', 'those', 'made', 'by', 'mice', 'and', 'other', 'small', 'animals'], ['in', 'one', 'people', 'deliberately', 'tamed', 'cats', 'in', 'a', 'process', 'of', 'artificial', 'selection', 'as', 'they', 'were', 'useful', 'predators', 'of', 'vermin'], ['the', 'domesticated', 'cat', 'and', 'its', 'closest', 'wild', 'ancestor', 'are', 'both', 'diploid', 'organism

In [ ]:
d = dict()
i = 0
for line in lines:
    for word in line:
        if word not in d:
            d[word] = i
            i += 1
          

In [ ]:
print(d)

{'in': 0, 'comparison': 1, 'to': 2, 'dogs': 3, 'cats': 4, 'have': 5, 'not': 6, 'undergone': 7, 'major': 8, 'changes': 9, 'during': 10, 'the': 11, 'domestication': 12, 'process': 13, 'as': 14, 'cat': 15, 'simply': 16, 'catenates': 17, 'streams': 18, 'of': 19, 'bytes': 20, 'it': 21, 'can': 22, 'be': 23, 'also': 24, 'used': 25, 'concatenate': 26, 'binary': 27, 'files': 28, 'where': 29, 'will': 30, 'just': 31, 'sequence': 32, 'a': 33, 'common': 34, 'interactive': 35, 'use': 36, 'for': 37, 'single': 38, 'file': 39, 'is': 40, 'output': 41, 'content': 42, 'standard': 43, 'hear': 44, 'sounds': 45, 'too': 46, 'faint': 47, 'or': 48, 'high': 49, 'frequency': 50, 'human': 51, 'ears': 52, 'such': 53, 'those': 54, 'made': 55, 'by': 56, 'mice': 57, 'and': 58, 'other': 59, 'small': 60, 'animals': 61, 'one': 62, 'people': 63, 'deliberately': 64, 'tamed': 65, 'artificial': 66, 'selection': 67, 'they': 68, 'were': 69, 'useful': 70, 'predators': 71, 'vermin': 72, 'domesticated': 73, 'its': 74, 'closest': 

In [ ]:
import numpy as np

In [ ]:
mas = np.zeros((len(lines), len(d)))

In [ ]:
def get_key(d, value): # функция ключа по его значению
    for k, v in d.items():
        if v == value:
            return k

In [ ]:
# Функция, подсчитывающая кол-во вхождений слова в строку
def word_counts(word, sentence):
  k = 0
  for i in range(len(sentence)):
    if word in sentence:
      k += 1
      return k

In [ ]:
for j in range(len(d)):
  for i in range(len(lines)): 
    mas[i,j] = word_counts(get_key(d,j), lines[i])

print(mas)

    # сколько раз j-ое слово из словаря вошло в i-ое предложение
    # Если слово из словаря содержится в 
    # lines - список предложений; sentence = lines[i] - предложение; word - слово


[[ 1.  1.  1. ... nan nan nan]
 [nan nan  1. ... nan nan nan]
 [nan nan  1. ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [ 1. nan  1. ... nan nan nan]
 [nan nan  1. ...  1.  1.  1.]]


In [ ]:
import scipy

In [ ]:
for i in range(len(lines)):
  for j in range(len(d)):
    if np.isnan(mas[i,j]):
      mas[i,j] = 0

In [ ]:
print(mas)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 1.]]


In [ ]:
from scipy.spatial import distance
distants = []
for i in range(len(mas)):
  distants.append(scipy.spatial.distance.cosine(mas[0,:], mas[i]))


In [ ]:
print(distants)


[0.0, 0.9402385695332803, 0.8619868881315291, 0.8885443574849294, 0.8055388829343507, 0.9351796276447836, 0.7547442642060137, 0.9154845745271484, 0.9069515789601529, 0.8833576312960392, 0.8703592552895671, 0.8703592552895671, 0.8773721321030068, 0.8703592552895671, 0.8619868881315291, 0.9402385695332803, 0.85361498905772, 0.9503708333014534, 0.9442721787424647, 0.9402385695332803, 0.8427572744917122, 0.8250364469440588]


In [ ]:
max = distants[0]
ind_max = 0
for i in range(1, len(distants)):
    if distants[i] > max:
      ind_max = i
      max = distants[i]
print(ind_max)
print(max)


17
0.9503708333014534


In [ ]:
sorted([(distants[i], i) for i in range(len(distants))])

[(0.0, 0),
 (0.7547442642060137, 6),
 (0.8055388829343507, 4),
 (0.8250364469440588, 21),
 (0.8427572744917122, 20),
 (0.85361498905772, 16),
 (0.8619868881315291, 2),
 (0.8619868881315291, 14),
 (0.8703592552895671, 10),
 (0.8703592552895671, 11),
 (0.8703592552895671, 13),
 (0.8773721321030068, 12),
 (0.8833576312960392, 9),
 (0.8885443574849294, 3),
 (0.9069515789601529, 8),
 (0.9154845745271484, 7),
 (0.9351796276447836, 5),
 (0.9402385695332803, 1),
 (0.9402385695332803, 15),
 (0.9402385695332803, 19),
 (0.9442721787424647, 18),
 (0.9503708333014534, 17)]

In [ ]:
help(scipy.spatial.distance.cosine)

Help on function cosine in module scipy.spatial.distance:

cosine(u, v, w=None)
    Compute the Cosine distance between 1-D arrays.
    
    The Cosine distance between `u` and `v`, is defined as
    
    .. math::
    
        1 - \frac{u \cdot v}
                  {||u||_2 ||v||_2}.
    
    where :math:`u \cdot v` is the dot product of :math:`u` and
    :math:`v`.
    
    Parameters
    ----------
    u : (N,) array_like
        Input array.
    v : (N,) array_like
        Input array.
    w : (N,) array_like, optional
        The weights for each value in `u` and `v`. Default is None,
        which gives each value a weight of 1.0
    
    Returns
    -------
    cosine : double
        The Cosine distance between vectors `u` and `v`.
    
    Examples
    --------
    >>> from scipy.spatial import distance
    >>> distance.cosine([1, 0, 0], [0, 1, 0])
    1.0
    >>> distance.cosine([100, 0, 0], [0, 1, 0])
    1.0
    >>> distance.cosine([1, 1, 0], [0, 1, 0])
    0.29289321881345